// <auto-generated />
namespace cozyjozywebapi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fixid43 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixid43));
        
        string IMigrationMetadata.Id
        {
            get { return "201502221250435_fixid43"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
