// <auto-generated />
namespace cozyjozywebapi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class fixid4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixid4));
        
        string IMigrationMetadata.Id
        {
            get { return "201502210314092_fixid4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
